### ISSUE TITLE
Support for /var/run/os-release

### ISSUE THREAD

**Issue by TCH69** [13-CF/aFetch#1]
so basically freebsd and other *BSD system use a /var/run/os-release that is generated everytime the system boots up instead of /etc/os-release on linux systems, so can you add support for the /var/run file alongside with the file in /etc/, in order to support BSD systems?
![Screenshot from 2020-09-27 21-36-30](https://user-images.githubusercontent.com/44942508/94367648-442c8080-010a-11eb-84c7-8f4d087072f9.png)

**Comment by 13-CF** [comment]
Hi, I think I have this working, so if the file doesn't exist in /etc then it'll search /var/run. It should be fixed in the next commit, along with support for FreeBSD, I've not added other logos yet though :(

**Comment by TCH69** [comment]
So, just use `pkg info`, it‘ll list out all  the packages that are installed. 
![Screenshot from 2020-09-28 11-57-28](https://user-images.githubusercontent.com/44942508/94392218-d6bc3680-0181-11eb-8bb8-97442df4e6b0.png)

**Comment by 13-CF** [comment]
Thanks, FreeBSD should now be fully supported.
