### ISSUE TITLE
zsh (core dumped)

### ISSUE THREAD

**Issue by TCH69** [13-CF/aFetch#14]
I re-cloned the repo agian and this time got this after compiling:
`IRM_x86_FREV [fa2_l]-[~/afetch] % ./afetch                           [INSERT]`
`/\,-'''''-,/\        USER fa2_l`
`zsh: segmentation fault (core dumped)  ./afetch`

**Comment by 13-CF** [comment]
If you edit the config file and set LOWERCASE to 1 does it fix it?

**Comment by TCH69** [comment]
Alright it's fixed now. But why it was set as 0 by default?

**Comment by 13-CF** [comment]
I keep forgetting to set the config back to the default settings when I upload the changes, I'll try to remember to set it back to defaults from now on.
