### ISSUE TITLE
Support for Slackware

### ISSUE THREAD

**Issue by MarlonRacCambasis** [13-CF/afetch#17]
I would like to add a request for you to add Slackware.
The `/etc/os-release` file looks like this:
```
NAME=Slackware
VERSION="14.2"
ID=slackware
VERSION_ID=14.2
PRETTY_NAME="Slackware 14.2"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:slackware:slackware_linux:14.2"
HOME_URL="http://slackware.com/"
SUPPORT_URL="http://www.linuxquestions.org/questions/slackware-14/"
BUG_REPORT_URL="http://www.linuxquestions.org/questions/slackware-14/"
```
I sincerely thank you in advanced.

**Comment by 13-CF** [comment]
Hi, I've (hopefully) added support for Slackware now. Please let me know if everything works properly, and if the package count displays correctly!

**Comment by MarlonRacCambasis** [comment]
Thank you! Looks all good to me, it is showing the right amount of packages as well.
