### ISSUE TITLE
Request distro

### ISSUE THREAD

**Issue by danrobi11** [13-CF/afetch#32]
Unable to locate package afetch

- MX 19.3 (patito feo) x86_64

```/etc/os-release```:

```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by 13-CF** [comment]
Hi, the program isn't any any repositories so you have to get the source and build it. You can do it with this one liner: `git clone https://github.com/13-CF/afetch.git; cd afetch; make; make install; afetch`. 

After this you can run the `afetch` command and it should work. Hope this helps!

**Comment by danrobi11** [comment]
Oh my bad. I obviously misunderstood. Yep, everything went fine. Really neat, Thank you! Therefore closing.
