### ISSUE TITLE
cannot stat './afetch'

### ISSUE THREAD

**Issue by canada-water** [13-CF/afetch#37]
Whenever I attempt to install this, it warns me that there is no ./afetch available for it to stat, and errors out. This was the case on Arch, Artix, Void, and Ubuntu. 
The output looks like this:

`install -o root -g root -d /usr/local/bin`

`install -o root -g root -d /usr/local/share/man/man1`

`install -o root -g root -m 711 ./afetch /usr/local/bin/afetch`

`install: cannot stat './afetch': No such file or directory`

`make: *** [Makefile:15: install] Error 1`

Not exactly sure what's happening with it.

**Comment by 13-CF** [comment]
Did you run `make` before running `make install`?

**Comment by SirCipherz** [comment]
I tried this on arch and artix, 13CF is probably right

**Comment by canada-water** [comment]
> Did you run make before running make install?

I just tried that and it still didn't work for me. This time, in fetch.c, it says ``unused variable 'pkgs'``

**Comment by 13-CF** [comment]
Are you using the latest version?

**Comment by canada-water** [comment]
As far as I know, I am. I did a git clone just a couple days ago.

**Comment by 13-CF** [comment]
Ok, `unused variable 'pkgs'` is just a compilation warning so you should still be able to execute it with `./afetch`.

**Comment by canada-water** [comment]
Ah, yep. Looks like it worked this time. Thanks!
