### ISSUE TITLE
displays a warning message during installation

### ISSUE THREAD

**Issue by opxop** [13-CF/afetch#38]
hi bro. thanks for creating this awesome tool, i appreciate it🤗

in this case, i want to ask you something. when i run command 'make' in wsl ubuntu 20.04, i got a warn message. is this okay?
![2021-01-05_21-52](https://user-images.githubusercontent.com/49778014/103662201-3a84a580-4fa2-11eb-9976-4ec84055d92e.png)

idk whether this problem should be fixed or not, but when i run 'afetch' is perfectly working.
![2021-01-05_21-52_1](https://user-images.githubusercontent.com/49778014/103663682-f2ff1900-4fa3-11eb-9af4-59406c8e37ac.png)

hmm, im sorry for missing my icons😓

**Comment by opxop** [comment]
and cat `cat /etc/os-release` outputs

```
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by 13-CF** [comment]
Hi, this shouldn't be an issue if the program still runs fine. 

Unfortunately I can't test it on every distro, so there may be compilation warnings on some of them. I use Debian 10 and there's no warnings, but perhaps Ubuntu in WSL uses a different version of GCC/libc.

**Comment by opxop** [comment]
its oke, good. 

and also my distro logo looks weired, where can i change that? i can't found dir afech inside `.config` folder

**Comment by 13-CF** [comment]
It doesn't read from a config file, you have to edit `src/config.h` to your liking, then `make clean`, `make` and `sudo make install`.

**Comment by opxop** [comment]
ah i see, thank you. its very helpful to me
