### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by SirCipherz** [13-CF/aFetch#4]
The project has no license, I would recommand a GPL3 license but if it was intended to not include a license you should add a public domain license.

**Comment by 13-CF** [comment]
Thanks! I didn't think about this, as this is my first proper project I've uploaded to GitHub. I'll go with the GPL3 license.

**Comment by astralchan** [comment]
https://www.gnu.org/licenses/gpl-howto.en.html
Is this `GPL-3.0-only` or `GPL-3.0-or-later`?
