### ISSUE TITLE
Missing Solus logo

### ISSUE THREAD

**Issue by ProbablyNotLime** [13-CF/afetch#46]
Hello! When I installed afetch on Solus it's don't show an ascii artwork however Solus is in the supported list.

**Comment by 13-CF** [comment]
Hi, I planned to create a logo logo for Solus using ASCII characters so I haven't got round to it.

None of the other fetch utilities have created a small logo, so it's something I'll have to do. I should be able to create it when I next have some free time, and I'll get back to you when I do. Thanks!

**Comment by ProbablyNotLime** [comment]
[solus.txt](https://github.com/13-CF/afetch/files/5937233/solus.txt)
I try to make a logo there it is.

**Comment by ProbablyNotLime** [comment]
I try to make a logo
[solus.txt](https://github.com/13-CF/afetch/files/5937235/solus.txt)

**Comment by 13-CF** [comment]
Hi, I've added your logo. If you pull the repo so you get the latest version then it should work.

**Comment by Dhruv-Vanjari** [comment]
Hi, I made one too.
```
    |\
   /  \|\-_
  /   |/ \ \
 '____----''''_
  \______---''
```
