### ISSUE TITLE
Parabola Linux request

### ISSUE THREAD

**Issue by KikooDX** [13-CF/afetch#47]
Hello, I would love to see Parabola supported by this tool. Thanks in advance! pfetch has a [small ASCII art for Parabola](https://github.com/dylanaraps/pfetch/blob/master/pfetch#L1529), it could be a good starting point. Here is the content of my `/etc/os-release`:
```
NAME="Parabola"
PRETTY_NAME="Parabola GNU/Linux-libre"
ID=parabola
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="1;35"
HOME_URL="https://www.parabola.nu/"
DOCUMENTATION_URL="https://wiki.parabola.nu/"
SUPPORT_URL="irc://chat.freenode.net#parabola"
BUG_REPORT_URL="https://labs.parabola.nu/"
LOGO=parabola
```
Wish you have a nice day!

**Comment by 13-CF** [comment]
Hello, I've just added parabola support, it should hopefully display the logo and package count now but I've not tested it.

**Comment by KikooDX** [comment]
Hello, it works well but the tags are offset.
```
  __ __ __  _      USER kdx
.`_//_//_/ / `.    DISTRO Parabola
          /  .`    KERNEL 5.10.6-gnu-1
         / .`    UPTIME 4h 55m
        /.`     SHELL fish
       /`      PKGS 546
```
I figured it should look like this:
```
  __ __ __  _        USER kdx
.`_//_//_/ / `.    DISTRO Parabola
          /  .`    KERNEL 5.10.6-gnu-1
         / .`      UPTIME 4h 55m
        /.`         SHELL fish
       /`             PKGS 546
```
Thank you for your support!

**Comment by 13-CF** [comment]
Hi, I've made an attempt to fix it so hopefully it works.

I'll probably have to make a special version of the program for printing different logos, cause it's too much of a hassle to set up a VM for every distro.

Thanks!

**Comment by KikooDX** [comment]
It works great, thank you. I close this issue :smile:
