### ISSUE TITLE
release workflow

### ISSUE THREAD

**Issue by tormath1** [13-CF/afetch#55]
Hi there, thanks a lot for this tool !

I see you only have a `stable` release tag. Is it plan to have a `v1`, `v2`, etc. ? It would be super helpful for people interested to package this software for various distributions in order to distribute it.

I would personally be interested to add it to Gentoo GURU overlay. :)

**Comment by KikooDX** [comment]
I agree, this would be very helpfull for packaging.

A simple version model I could think of would be `vX.Y.Z`, with X being
a big structural change, Y addition of one or multiple targets and Z
other kinds of changes (like speed increase of a package count command).

**Comment by tormath1** [comment]
@KikooDX that could be a good starting point. :) It's actually pretty similar to https://semver.org/

**Comment by 13-CF** [comment]
Hi there! I think this is a great idea, and that @KikooDX has a good way of determining the release version.

I'm actually rewriting the program just now, using the pthreads API (for multithreading) to speed things up a bit, so that would be a great `V2`.

I'll finish adding support for a couple of distros, then upload my `V2` code once it's been thoroughly tested.

**Comment by 13-CF** [comment]
Hello again, I've (mostly) finished rewriting the program, so I've started to release certain versions. I've not fully tested it for every Linux distro, but it seems to work on one of them and most are the same, so hopefully it's ok on the untested ones!

**Comment by tormath1** [comment]
@13-CF Indeed. I see the `V2.0`; it will be easier for people interested to package `afetch`. Thanks !

However on my Gentoo; it does not seem to work:

```bash
$  git clone https://github.com/13-CF/afetch
$ git checkout V2.0
HEAD is now at 270e161 Version 2 - with multithreading
$ make afetch
cc -O2 -std=c99 -Wall -Wextra src/fetch.c -lpthread -o afetch
src/fetch.c: In function ‘pipeRead’:
src/fetch.c:29:2: warning: ignoring return value of ‘fscanf’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   29 |  fscanf(pipe, "%[^\n]s", returnVal);
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
$ ./afetch
```

Then it freezes.

```
$ cc --version
cc (Gentoo 10.2.0-r5 p6) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

I will open a dedicated issue to close this one. Let me know if you need more information to help you debugging.
