### ISSUE TITLE
gentoo package provided

### ISSUE THREAD

**Issue by tormath1** [13-CF/afetch#60]
Hi, following the issue https://github.com/13-CF/afetch/issues/55: package has been added to the Gentoo GURU [overlay](https://github.com/gentoo/guru).

User can install `afetch` and save the `src/config.h` using `savedconfig` flag in order to preserve the config between each release. 

```
[ebuild  N    ~] app-misc/afetch-2.0.1  USE="savedconfig"
```

Here's the badge; if you want to add it to the README: 
[![Gentoo overlay GURU package](https://repology.org/badge/version-for-repo/gentoo_ovl_guru/afetch.svg)](https://repology.org/project/afetch/versions)

**Comment by 13-CF** [comment]
Thanks, I'll add the badge to the README! You mentioned that the user can preserve their config between releases, but couldn't that prevent the new program from compiling due to certain config options being undefined in the old `src/config.h`?

**Comment by KikooDX** [comment]
Very nice! If you are going to add badges/packages to the README, probably add this one status badge that summerizes for all supported distros at once.
```md
[![Packaging status](https://repology.org/badge/vertical-allrepos/afetch.svg)](https://repology.org/project/afetch/versions)
```
[![Packaging status](https://repology.org/badge/vertical-allrepos/afetch.svg)](https://repology.org/project/afetch/versions)

**Comment by tormath1** [comment]
> Thanks, I'll add the badge to the README! You mentioned that the user can preserve their config between releases, but couldn't that prevent the new program from compiling due to certain config options being undefined in the old `src/config.h`?

@13-CF that's a good question. In case you are not familiar with Gentoo: `savedconfig` option will save the `src/config.h` in a dedicated file `/etc/portage/savedconfig/app-misc/afetch-2.0.1`. According to the [documentation](https://dev.gentoo.org/~zmedico/portage/doc/man/emerge.1.html) (CONFIGURATION FILES section): 
> When Portage installs a file into a protected directory tree like /etc, any existing files will not  be  over‐written.  If  a file of the same name already exists, Portage will change the name of the to-be-installed file from 'foo' to ´._cfg0000_foo´. If ´._cfg0000_foo´ already exists, this name becomes ´._cfg0001_foo´,  etc.  In this  way,  existing  files  are  not overwritten, allowing the administrator to manually merge the new config files and avoid any unexpected changes.

Using `etc-update` or `dispatch-conf` user will be able to update its config in case a new one is provided.

**Comment by 13-CF** [comment]
@tormath1  Ah, that makes sense! It doesn't seem like it would be too problematic. I've added the package info to the README, I'll probably tweak it a bit more to make it look a bit nicer. Thanks!
