### ISSUE TITLE
Distribution request: Linux Mint and LMDE

### ISSUE THREAD

**Issue by LambLeeg** [13-CF/afetch#69]
So, I am a little curious that these distros are not here but something exotic for desktop like NetBSD is here. I mean, LM one of the most wide known distro, and it's not here and its Debian version aka LMDE either. So, could you add both, please?

**Comment by 13-CF** [comment]
Hi, I should be able to do this today, I'm currently downloading the ISO files for the latest versions of both so I can do testing but the mirrors are very slow, so I think I'll be able to do it in the next few hours. Thanks.

**Comment by LambLeeg** [comment]
> Hi, I should be able to do this today, I'm currently downloading the ISO files for the latest versions of both so I can do testing but the mirrors are very slow, so I think I'll be able to do it in the next few hours. Thanks.

Thank you!

**Comment by 13-CF** [comment]
I've just added support for Linux Mint, LMDE hasn't downloaded yet so I'll have to do it later. Thanks!
