### ISSUE TITLE
colour blocks dont seem to be working

### ISSUE THREAD

**Issue by derpyzza** [13-CF/afetch#74]
hello! as the title states, colour blocks dont seem to be working for me.
im on pop os, and i double checked my config.h file's contents, and where it's placed, and it all seems to be fine. the config file is located at ~/.config/afetch/config.h, and the contents are as follows:
`#define PrintColours    true
#define ColourCharacter ""`
it still dosent seem to be printing out the colour blocks.
im sorry if this has been asked before, and if im overlooking something dumb :sweat_smile:

**Comment by KikooDX** [comment]
Hello derpyzza. afetch is configured at compile-time, what that means is than you need to modify `src/config.h` and recompile the software (with `make`) to see the changes. And no need to be sorry, it's OK to ask for help 😄

In case you don't know how to build and install afetch from source, here is the full process:
```
$ #make sure you uninstalled afetch from your package manager
$ git clone https://github.com/13-CF/afetch
$ cd afetch
$ make
# make install
$ afetch
```

**Comment by derpyzza** [comment]
ohhhh, i read that it was configured at compile time, but i didn't realise i had to actually, you know, recompile it. my bad! thank you so much for answering! :smile:
