### ISSUE TITLE
fetch.c undefined reference to sysinfo'

### ISSUE THREAD

**Issue by TCH69** [13-CF/aFetch#8]
So, I'm here agian, this time compiling the program on my FreeBSD machine, but got this instead. I already have glib, glibmm, libsysinfo and sysinfo installed, even though I don't know what dependencies do the program need. 
![Screenshot from 2020-09-29 17-45-49](https://user-images.githubusercontent.com/44942508/94548986-b83a6600-027b-11eb-8434-c4ef16fb22bd.png)

**Comment by 13-CF** [comment]
On most Linux distros it shouldn't have any dependencies, but I wasn't aware that there was issues compiling on FreeBSD. I read [this](https://forums.freebsd.org/threads/porting-nomacs-using-sysinfo-h-linking-the-sysinfo-object-fails.33986/), and it seems that the linker fails to use libsysinfo.  

Does `ldd /usr/local/lib/libsysinfo.so` give any errors? In the forum post the user says their issue was solved by adding `-lkvm` to their Makefile, but then that might add another dependency that isn't included in the base install of FreeBSD. 

Could you try running `gcc fetch.c -lsysinfo` and `gcc fetch.c -lkvm`? (if you have kvm libs)

**Comment by TCH69** [comment]
Oh it works now, I'll close this issue.
